####################################
#  M O N S T E R  M A N I F E S T  #
####################################

- name: Rat
  description: >
    A rodent of relatively usual size.
  renderable:
    glyph: "r"
    fg: "#FF0000"
    index: 1
  spawn:
    min_floor: 0
    base_weight: 20
  viewshed:
    range: 6
  stats:
    hp:
      current: 4
      max: 4
    mp:
      current: 0
      max: 0
    exp:
      current: 0
      max: 0
    level: 1
    strength: 9
    dexterity: 9
    constitution: 9
    intelligence: 9
    wisdom: 9
    charisma: 9
  drop_type: Animal

- name: Snake
  description: >
    Slimy and slithery with beady, hungry eyes.
  renderable:
    glyph: "s"
    fg: "#FF0000"
    index: 1
  spawn:
    min_floor: 0
    base_weight: 15
  viewshed:
    range: 8
  stats:
    hp:
      current: 5
      max: 5
    mp:
      current: 0
      max: 0
    exp:
      current: 0
      max: 0
    level: 1
    strength: 9
    dexterity: 9
    constitution: 9
    intelligence: 9
    wisdom: 9
    charisma: 9
  drop_type: Animal

- name: Bat
  description: >
    Small and furry, kinda cute honestly. Oh fuck, are those fangs?
  renderable:
    glyph: "b"
    fg: "#FF0000"
    index: 1
  spawn:
    min_floor: 0
    base_weight: 15
  viewshed:
    range: 10
  stats:
    hp:
      current: 5
      max: 5
    mp:
      current: 0
      max: 0
    exp:
      current: 0
      max: 0
    level: 1
    strength: 9
    dexterity: 9
    constitution: 9
    intelligence: 9
    wisdom: 9
    charisma: 9
  drop_type: Animal

- name: Mangy Wolf
  description: >
    Small (for a wolf). All teeth, growls, and matted fur. Looks hungry.
  renderable:
    glyph: "w"
    fg: "#FF0000"
    index: 1
  spawn:
    min_floor: 0
    base_weight: 15
  viewshed:
    range: 10
  stats:
    hp:
      current: 8
      max: 8
    mp:
      current: 0
      max: 0
    exp:
      current: 0
      max: 0
    level: 2
    strength: 10
    dexterity: 12
    constitution: 9
    intelligence: 9
    wisdom: 9
    charisma: 9
  drop_type: Animal

- name: Goblin
  description: >
    It's a goblin. Smaller than you, but with a cruel smile that makes you
    uncomfortable.
  renderable:
    glyph: "g"
    fg: "#FF0000"
    index: 1
  spawn:
    min_floor: 1
    base_weight: 10
  viewshed:
    range: 8
  stats:
    hp:
      current: 10
      max: 10
    mp:
      current: 0
      max: 0
    exp:
      current: 0
      max: 0
    level: 2
    strength: 11
    dexterity: 11
    constitution: 10
    intelligence: 9
    wisdom: 9
    charisma: 9
  drop_type: Goblin

- name: Orc
  description: >
    Angry, ugly, and mean. These creatures are human sized but
    feral and bred for war.
  renderable:
    glyph: "o"
    fg: "#FF0000"
    index: 1
  spawn:
    min_floor: 1
    base_weight: 10
  viewshed:
    range: 8
  stats:
    hp:
      current: 20
      max: 20
    mp:
      current: 0
      max: 0
    exp:
      current: 0
      max: 0
    level: 3
    strength: 12
    dexterity: 10
    constitution: 12
    intelligence: 10
    wisdom: 10
    charisma: 10
  drop_type: Orc

- name: Orc Captain
  description: >
    Only the meanest and most cunning orcs live long enough to ascend to
    leadership, this one is no exception.
  renderable:
    glyph: "O"
    fg: "#FF0000"
    index: 1
  spawn:
    min_floor: 1
    base_weight: 5
  viewshed:
    range: 8
  stats:
    hp:
      current: 25
      max: 25
    mp:
      current: 0
      max: 0
    exp:
      current: 0
      max: 0
    level: 5
    strength: 13
    dexterity: 11
    constitution: 12
    intelligence: 10
    wisdom: 10
    charisma: 10
  drop_type: Orc